# elixir.yaml

name: Elixir CI

on: [pull_request]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test_1-4:
    uses: ./.github/workflows/reusable_elixir.yaml
    secrets:
      partition: "1"
      partitions: "4"
  test_2-4:
    uses: ./.github/workflows/reusable_elixir.yaml
    secrets:
      partition: "2"
      partitions: "4"
  test_3-4:
    uses: ./.github/workflows/reusable_elixir.yaml
    secrets:
      partition: "3"
      partitions: "4"
  test_4-4:
    uses: ./.github/workflows/reusable_elixir.yaml
    secrets:
      partition: "4"
      partitions: "4"